Transform: AWS::Serverless-2016-10-31
Resources:  
  createmyTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        -
          AttributeName: "Name"
          AttributeType: "S"
        -
          AttributeName: "ID"
          AttributeType: "N"
      KeySchema:
        -
          AttributeName: "ID"
          KeyType: "HASH"
        -
          AttributeName: "Name"
          KeyType: "RANGE"
      TableName: "myDynamoTable"
      ProvisionedThroughput: 
        ReadCapacityUnits: "1"
        WriteCapacityUnits: "1"
