Transform: AWS::Serverless-2016-10-31
Resources:
  mylambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: myfirstlambda.lambda_handler
      Runtime: python3.10
      FunctionName: myfirstlambda
      CodeUri: s3://lijobucket/6fbe3d88781d04390dd1a36d895ce558
      Role: arn:aws:iam::900835517207:role/service-role/MyFirstFunction-role-dwts5yyc
      Timeout: 100
  createabucketlambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: createandlistbucket.lambda_handler
      Runtime: python3.10
      FunctionName: createandlistbucket
      CodeUri: s3://lijobucket/6fbe3d88781d04390dd1a36d895ce558
      Role: arn:aws:iam::900835517207:role/service-role/MyFirstFunction-role-dwts5yyc
      Timeout: 100
