Transform: AWS::Serverless-2016-10-31
Resources:
  mylambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: myfirstlambda.lambda_handler
      Runtime: python3.10
      FunctionName: myfirstlambda
      CodeUri: s3://lijobucket/71585a4d5750c42e0a1e9b56122a0522
      Role: arn:aws:iam::900835517207:role/service-role/MyFirstFunction-role-dwts5yyc
      Timeout: 100
